enum GameState {BOOT, MENU, PLAYING, PAUSED, GAME_OVER}
enum LevelState {NONE, INITIALIZING, SHIP_SELECT, PLAYING, COMPLETE, FAILED, EXITING}
enum PlayerState {INITIALIZING, ACTIVE, STUNNED, DISABLED, DESTROYED}
enum MainMenuAction {DEPLOY, HANGAR, OPTIONS, CHANGE_PROFILE, EXIT}
enum EnemyState { IDLE, CHASING, ATTACKING, STUNNED, DEAD }
enum Faction { PLAYER, SIMULANT, REBEL, CORPORATION, ALIEN }
enum AttackSelection { SEQUENTIAL, RANDOM, WEIGHTED }
enum AttackDelivery { PROJECTILE, AREA }
enum AimMode { MOUNT, TARGET, TARGET_LEAD, WORLD }
enum ShotPattern { SINGLE, SPREAD, RANDOM_CONE }
enum HardpointFireOrder { ALL, SEQUENTIAL, RANDOM }
enum DamageType { KINETIC, ENERGY, EXPLOSIVE, ELECTRIC, THERMAL, CORROSIVE }
enum DamageEffect { NONE, DISRUPTION, BURN, CORROSION }