enum GameState {BOOT, MENU, PLAYING, PAUSED, GAME_OVER}
enum LevelState {NONE, INITIALIZING, SHIP_SELECT, PLAYING, COMPLETE, FAILED, EXITING}
enum PlayerState { INITIALIZING, ACTIVE, DASHING, STUNNED, DISABLED, DESTROYED }
enum MainMenuAction {DEPLOY, HANGAR, OPTIONS, CHANGE_PROFILE, EXIT}
enum EnemyState { IDLE, CHASING, ATTACKING, STUNNED, DEAD }
enum Faction { PLAYER, SIMULANT, REBEL, CORPORATION, ALIEN }
enum AttackSelection { SEQUENTIAL, RANDOM, WEIGHTED }
enum AttackDelivery { PROJECTILE, AREA, BEAM }
enum AttackAreaShape { CIRCLE, CAPSULE, CONE }
enum EnemyAttackPhase { IDLE, TELEGRAPH, ACTIVE, COOLDOWN }
enum WeaponMountMode { HARDPOINT, CENTRE }
enum AimMode { MOUNT, TARGET, TARGET_LEAD, WORLD }
enum ShotPattern { SINGLE, SPREAD, RANDOM_CONE }
enum HardpointFireOrder { ALL, SEQUENTIAL, RANDOM }
enum HardpointRotation { FIXED, TARGET }
enum DamageType { KINETIC, ENERGY, EXPLOSIVE, ELECTRIC, THERMAL, CORROSIVE }
enum DamageEffect { NONE, DISRUPTION, BURN, CORROSION, STAGGER }
enum ProjectileClass { LIGHT, REGULAR, HEAVY }
enum ProjectileState { ACTIVE, RICOCHET }
enum DefenceLayer { NONE, SHIELD, ARMOUR, HULL }
enum ResourceType { NONE, ENERGY, FUEL, BULLETS, EXPLOSIVES }